kafka:
  topic: 'ese-orders-app'
  consumer:
    group.id: dev_order
    auto.offset.reset: earliest
instrument:
  filepath: '/mnt/c/Users/vipin/work/spaassignmentdata/instruments.csv'
bulkorder:
  filepath: '/mnt/c/Users/vipin/work/spaassignmentdata/bulkorder.csv'