kafka:
  order_topic: 'ese-orders-app'
  reorder_topic: 'ese-re-orders'
  matched_topic: 'ese-matched-orders'
  consumer:
    order.group.id: dev_order
    reorder.group.id: dev_order
    auto.offset.reset: earliest
instrument:
  filepath: '/mnt/c/Users/vipin/work/spaassignmentdata/instruments.csv'
bulkorder:
  filepath: '/mnt/c/Users/vipin/work/spaassignmentdata/bulkorder.csv'