kafka:
  order_topic: 'ese-orders-app'
  reorder_topic: 'ese-re-orders'
  matched_topic: 'ese-matched-orders'
  batch_duration: "5 seconds"
  consumer:
    order.group.id: dev_order
    reorder.group.id: dev_reorder
    auto.offset.reset: earliest
  checkpoint.dir: "file:///mnt/c/Users/vipin/work/spaassignmentdata/"
matchmaker:
  filepath: './data/instruments.csv'