kafka:
  topic: 'ese-orders-app'
  batch_duration: "5 seconds"
  consumer:
    group.id: dev_order
    auto.offset.reset: earliest
  checkpoint.dir: "file:///mnt/c/Users/vipin/work/spaassignmentdata/"
matchmaker:
  filepath: './data/instruments.csv'